//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERP.Web.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class KH_POLICY
    {
        public int ID { get; set; }
        public string MA_KHACH_HANG { get; set; }
        public string MA_NHOM_HANG { get; set; }
        public Nullable<decimal> GIA_BAN { get; set; }
        public Nullable<decimal> CHIET_KHAU_CM { get; set; }
        public string GHI_CHU { get; set; }
        public string THOI_GIAN_AP_DUNG { get; set; }
    
        public virtual HH_NHOM_VTHH HH_NHOM_VTHH { get; set; }
        public virtual KH KH { get; set; }
    }
}
